
[34m[1mwandb[39m[22m:   4 of 4 files downloaded.
Traceback (most recent call last):
  File "/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/test_model/run.py", line 122, in <module>
    go(args)
  File "/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/test_model/run.py", line 74, in go
    date = datetime.datetime.now().strftime('%Y-%m-%d')
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'