Traceback (most recent call last):
  File "/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/training_validation/run.py", line 160, in <module>
    go(args)
  File "/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/training_validation/run.py", line 62, in go
    xgboost = inference(xgb_config)
  File "/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/training_validation/run.py", line 112, in inference
    xgboost = model.get_booster()
  File "/home/orestas41/miniconda3/envs/mlflow-2607edbc4612998530e14928de78596a3fc9fc6f/lib/python3.10/site-packages/xgboost/sklearn.py", line 649, in get_booster
    raise NotFittedError("need to call fit or load_model beforehand")
sklearn.exceptions.NotFittedError: need to call fit or load_model beforehand