2023-05-04 11:09:35,976 Merging multiple dataframes
/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/pre-processing/run.py:40: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(df)
/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/pre-processing/run.py:40: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(df)
/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/pre-processing/run.py:40: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(df)
/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/pre-processing/run.py:40: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(df)
/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/pre-processing/run.py:40: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(df)
/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/pre-processing/run.py:40: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(df)
/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/pre-processing/run.py:40: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(df)
2023-05-04 11:09:36,129 Creating dataframe
2023-05-04 11:09:36,139 Removeing rows with missing values
2023-05-04 11:09:36,144 Converting Date column into datetime format
2023-05-04 11:09:36,176 Setting Date column as index
2023-05-04 11:09:36,178 Checking if teams are correct. Changing if incorrect
2023-05-04 11:09:36,178 Checking the teams are on the correct side. Changing if incorrect
2023-05-04 11:09:36,178 Converting Results columns into separate columns for Home and Away goals
2023-05-04 11:09:36,187 Encoding unique strings
2023-05-04 11:09:36,188 Creating Winner column with the team that won or draw
2023-05-04 11:09:36,189 Converting date into datetime format
Traceback (most recent call last):
  File "/home/orestas41/miniconda3/envs/mlflow-0fb78b63611cf0d39492e26261883faf819037da/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'last_review'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/pre-processing/run.py", line 164, in <module>
    go(args)
  File "/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/pre-processing/run.py", line 106, in go
    df['last_review'] = pd.to_datetime(df['last_review'])
  File "/home/orestas41/miniconda3/envs/mlflow-0fb78b63611cf0d39492e26261883faf819037da/lib/python3.10/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/orestas41/miniconda3/envs/mlflow-0fb78b63611cf0d39492e26261883faf819037da/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'last_review'