2023-05-30 17:42:44,293 INFO    MainThread:31421 [wandb_setup.py:_flush():76] Current SDK version is 0.15.2
2023-05-30 17:42:44,293 INFO    MainThread:31421 [wandb_setup.py:_flush():76] Configure stats pid to 31421
2023-05-30 17:42:44,293 INFO    MainThread:31421 [wandb_setup.py:_flush():76] Loading settings from /home/orestas41/.config/wandb/settings
2023-05-30 17:42:44,293 INFO    MainThread:31421 [wandb_setup.py:_flush():76] Loading settings from /home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/training_validation/wandb/settings
2023-05-30 17:42:44,294 INFO    MainThread:31421 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'run_group': 'development', 'project': 'project-FootballPredict'}
2023-05-30 17:42:44,294 INFO    MainThread:31421 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-30 17:42:44,294 INFO    MainThread:31421 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'training_validation/run.py', 'program': '/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/training_validation/run.py'}
2023-05-30 17:42:44,294 INFO    MainThread:31421 [wandb_init.py:_log_setup():507] Logging user logs to /home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/training_validation/wandb/run-20230530_174244-9tng73d3/logs/debug.log
2023-05-30 17:42:44,294 INFO    MainThread:31421 [wandb_init.py:_log_setup():508] Logging internal logs to /home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/training_validation/wandb/run-20230530_174244-9tng73d3/logs/debug-internal.log
2023-05-30 17:42:44,294 INFO    MainThread:31421 [wandb_init.py:init():547] calling init triggers
2023-05-30 17:42:44,294 INFO    MainThread:31421 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-05-30 17:42:44,294 INFO    MainThread:31421 [wandb_init.py:init():596] starting backend
2023-05-30 17:42:44,294 INFO    MainThread:31421 [wandb_init.py:init():600] setting up manager
2023-05-30 17:42:44,296 INFO    MainThread:31421 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-05-30 17:42:44,299 INFO    MainThread:31421 [wandb_init.py:init():606] backend started and connected
2023-05-30 17:42:44,300 INFO    MainThread:31421 [wandb_init.py:init():700] updated telemetry
2023-05-30 17:42:44,307 INFO    MainThread:31421 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-05-30 17:42:45,362 WARNING MainThread:31421 [wandb_init.py:init():1172] interrupted
Traceback (most recent call last):
  File "/home/orestas41/miniconda3/envs/mlflow-2607edbc4612998530e14928de78596a3fc9fc6f/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1150, in init
    run = wi.init()
  File "/home/orestas41/miniconda3/envs/mlflow-2607edbc4612998530e14928de78596a3fc9fc6f/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 740, in init
    result = run_init_handle.wait(
  File "/home/orestas41/miniconda3/envs/mlflow-2607edbc4612998530e14928de78596a3fc9fc6f/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/orestas41/miniconda3/envs/mlflow-2607edbc4612998530e14928de78596a3fc9fc6f/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/orestas41/miniconda3/envs/mlflow-2607edbc4612998530e14928de78596a3fc9fc6f/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/orestas41/miniconda3/envs/mlflow-2607edbc4612998530e14928de78596a3fc9fc6f/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/home/orestas41/miniconda3/envs/mlflow-2607edbc4612998530e14928de78596a3fc9fc6f/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-05-30 17:42:52,029 WARNING MsgRouterThr:31421 [router.py:message_loop():77] message_loop has been closed
